version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: ticket_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_booking_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

  backend:
    build: ./backend
    container_name: ticket_backend
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/ticket_booking_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: root
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      JWT_SECRET: ticketbookingsecretkeyticketbookingsecretkey123456
    ports:
      - "8080:8080"

volumes:
  mysql_data:
